import TabPanelUnstyled from "@mui/base/TabPanelUnstyled";
import {
  Button,
  Container,
  Divider,
  Grid,
  Paper,
  Slide,
  Stack,
  Typography,
  useMediaQuery,
  useTheme
} from "@mui/material";
import { grey } from "@mui/material/colors";
import { styled } from "@mui/system";
import Head from "next/head";
import Image from "next/image";
import { useSelector } from "react-redux";
import Typewriter from "typewriter-effect";
import styles from "../styles/Home.module.css";

const TabPanel = styled(TabPanelUnstyled)(
  ({ theme }) => `
  width: 100%;
  height: 100%;
  font-family: IBM Plex Sans, sans-serif;
  font-size: 0.875rem;
  padding: 20px 12px;
  background: transparent;
  border: 1px solid ${theme.palette.mode === "dark" ? grey[700] : grey[200]};
  border-radius: 12px;

  `
);

const tiers = [
  {
    title: "Free",
    price: "0",
    description: [
      "10 users included",
      "2 GB of storage",
      "Help center access",
      "Email support",
    ],
    buttonText: "Sign up for free",
    buttonVariant: "outlined",
  },
  {
    title: "Pro",
    subheader: "Most popular",
    price: "15",
    description: [
      "20 users included",
      "10 GB of storage",
      "Help center access",
      "Priority email support",
    ],
    buttonText: "Get started",
    buttonVariant: "contained",
  },
  {
    title: "Enterprise",
    price: "30",
    description: [
      "50 users included",
      "30 GB of storage",
      "Help center access",
      "Phone & email support",
    ],
    buttonText: "Contact us",
    buttonVariant: "outlined",
  },
];

export default function Home() {
  const {
    app: { tabValue },
  } = useSelector((state) => state);

  const theme = useTheme()
  const breakpoints_xs = useMediaQuery(theme.breakpoints.up("sm"));

  const time = setTimeout(() => {
    console.log('Hello, World!')
  }, 3000)

  console.log(time)

  return (
    <div className={styles.container}>
      <Head>
        <title>CodeLines WEB</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Grid
        container
        direction="row"
        justifyContent="space-evenly"
        alignItems="center"
        spacing={3}
        sx={{ padding: 1 }}
      >
        <Grid item xs={12} sm={7} md={7} lg={7} xl={7}>
          <Slide direction="up" in={true} mountOnEnter unmountOnExit>
            <Stack alignContent={"end"} alignItems="end">

              <Typography
                component="h2"
                variant="h3"
                align="right"
                color="white"
                gutterBottom
              >
                <Typography
                  component="h1"
                  variant="h1"
                  align="right"
                  color="white"
                  gutterBottom
                ><b>
                    <Typewriter
                      options={{
                        autoStart: true,
                      }}
                      onInit={(typewriter) => {
                        typewriter.pauseFor(1500).typeString("CODE LINES").start();
                      }}
                    />
                  </b>
                </Typography>
                <Typewriter
                  options={{
                    loop: true,
                    autoStart: true,
                  }}
                  onInit={(typewriter) => {
                    typewriter
                      .pauseFor(2500)
                      .typeString("EN LA NUBE")
                      .pauseFor(2500)
                      .deleteChars(11)
                      .start();
                  }}
                />
                <Typewriter
                  options={{
                    loop: true,
                    autoStart: true,
                  }}
                  onInit={(typewriter) => {
                    typewriter
                      .pauseFor(3500)
                      .typeString("ESCALABLE")
                      .pauseFor(3500)
                      .deleteChars(11)
                      .start();
                  }}
                />
                <Typewriter
                  options={{
                    loop: true,
                    autoStart: true,
                  }}
                  onInit={(typewriter) => {
                    typewriter
                      .pauseFor(4500)
                      .typeString("MÁS RÁPIDO")
                      .pauseFor(4500)
                      .deleteChars(11)
                      .start();
                  }}
                />
                <Typewriter
                  options={{
                    loop: true,
                    autoStart: true,
                  }}
                  onInit={(typewriter) => {
                    typewriter
                      .pauseFor(5500)
                      .typeString("OFF-LINE")
                      .pauseFor(5500)
                      .deleteChars(11)
                      .start();
                  }}
                />
              </Typography>



            </Stack>
          </Slide>
        </Grid>
        <Grid item xs={12} sm={5} md={5} lg={5} xl={5}>

          {breakpoints_xs ?
          <Image
          src="/img/logo60.webp"
          alt="CodeLines Logo"
          width={255}
          height={255}
          sizes="100vw"
          style={{
            width: '100%',
            height: 'auto',
          }}
        />
          :
          
          <Image
            src="/img/app-control-logo.webp"
            alt="CodeLines Logo"
            width={355}
            height={105}
            sizes="100vw"
            style={{
              width: '100%',
              height: 'auto',
            }}
          />}
          <Stack alignContent={'center'} alignItems='center' sx={{ m: 3 }} >
            <Button size="large" color='info' variant="contained" sx={{ width: '100%' }}>
              Saber Más
            </Button>
          </Stack>

        </Grid>



      </Grid>
    </div>
  );
}
