import {
  Grid, Slide,
  Stack,
  Typography,
  useMediaQuery,
  useTheme
} from "@mui/material";
import Head from "next/head";
import Image from "next/image";
import { useSelector } from "react-redux";
import Typewriter from "typewriter-effect";
import styles from "../styles/Home.module.css";



export default function Home() {
  const {
    app: { loading_pag },
  } = useSelector((state) => state);

  const theme = useTheme();
  const breakpoints_xs = useMediaQuery(theme.breakpoints.up("sm"));

  function LogoApp() {
    return (
      <Image
        src="/img/logo60wi.webp"
        alt="CodeLines Logo"
        width={255}
        height={255}
        sizes="100vw"
        style={{
          width: "100%",
          height: "auto",
        }}
      />
    );
  }

  function Texto() {
    return (
      <Slide direction="up" in={true} mountOnEnter unmountOnExit>
        <Stack alignContent={"end"} alignItems="end">
          <Typography
            component="h2"
            variant="h3"
            align="right"
            color="white"
            gutterBottom
          >
            <Typography
              component="h2"
              variant="h2"
              align="right"
              color="white"
              gutterBottom
            >
              <b>
                <Typewriter
                  options={{
                    autoStart: true,
                  }}
                  onInit={(typewriter) => {
                    typewriter.pauseFor(1500).typeString("CODE LINES").start();
                  }}
                />
              </b>
            </Typography>
            <Typography
              component="h5"
              variant="h5"
              align="right"
              color="white"
              gutterBottom
            >
              <b>
                <Typewriter
                  options={{
                    autoStart: true,
                  }}
                  onInit={(typewriter) => {
                    typewriter
                      .pauseFor(1500)
                      .typeString("APLICACIONES")
                      .start();
                  }}
                />
              </b>
            </Typography>

            <Typewriter
              options={{
                loop: true,
                autoStart: true,
              }}
              onInit={(typewriter) => {
                typewriter
                  .pauseFor(2500)
                  .typeString("EN LA NUBE")
                  .pauseFor(7500)
                  .deleteAll()
                  .start();
              }}
            />
            <Typewriter
              options={{
                loop: true,
                autoStart: true,
              }}
              onInit={(typewriter) => {
                typewriter
                  .pauseFor(4500)

                  .typeString("ADAPTABLES")
                  .pauseFor(5500)
                  .deleteAll()
                  .start();
              }}
            />
            <Typewriter
              options={{
                loop: true,
                autoStart: true,
              }}
              onInit={(typewriter) => {
                typewriter
                  .pauseFor(6500)
                  .typeString("ESCALABLES")
                  .pauseFor(3500)
                  .deleteAll()
                  .start();
              }}
            />
            <Typewriter
              options={{
                loop: true,
                autoStart: true,
              }}
              onInit={(typewriter) => {
                typewriter
                  .pauseFor(8500)
                  .typeString("MÁS RÁPIDAS")
                  .pauseFor(1500)
                  .deleteAll()
                  .start();
              }}
            />
          </Typography>
        </Stack>
      </Slide>
    );
  }


  if(loading_pag){
    return null
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>CodeLines WEB</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Grid
        container
        direction="row"
        justifyContent="space-evenly"
        alignItems="center"
        spacing={3}
        sx={{ padding: 1 }}
      > 
        <Grid item xs={9} sm={7} md={7} lg={7} xl={7}>
          {breakpoints_xs ? <Texto /> : <LogoApp />}
        </Grid>
        <Grid item xs={12} sm={4} md={4} lg={4} xl={4}>
          {breakpoints_xs ? <LogoApp /> : <Texto />}
        </Grid>

      
      </Grid>
    </div>
  );
}
