import TabPanelUnstyled from "@mui/base/TabPanelUnstyled";
import {
  Button,
  Container,
  Divider,
  Grid,
  ImageList,
  ImageListItem,
  Paper,
  Slide,
  Stack,
  Typography,
  useMediaQuery,
  useTheme,
} from "@mui/material";
import { grey } from "@mui/material/colors";
import { styled } from "@mui/system";
import Head from "next/head";
import Image from "next/image";
import { useSelector } from "react-redux";
import Typewriter from "typewriter-effect";
import CardModules from "../components/CardModules";
import styles from "../styles/Home.module.css";

export default function Modulos() {

  const {
    app: { loading_pag },
  } = useSelector((state) => state);

  if(loading_pag){
    return null
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>CodeLines WEB</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ImageList
      
        variant="masonry"
        cols={3}
        gap={2}
      >
        <ImageListItem>
          <CardModules />
        </ImageListItem>
        <ImageListItem>
          <CardModules />
        </ImageListItem>
        <ImageListItem>
          <CardModules />
        </ImageListItem>
        <ImageListItem>
          <CardModules />
        </ImageListItem>
        <ImageListItem>
          <CardModules />
        </ImageListItem>
        <ImageListItem>
          <CardModules />
        </ImageListItem>
      </ImageList>
    </div>
  );
}
